name: Export to pdf and epub
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  en_us_pdf:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout markdown
        uses: actions/checkout@v3

      - name: Create paths
        run: mkdir -p publish

      - name: Export to pdf
        uses: docker://pandoc/latex:3.1
        with:
          args: >-
            --output publish/OWASP_SCP_Quick_Reference_Guide.en-US.pdf
            _draft/en/us/title.pdf.yaml
            _draft/en/us/01-introduction/01-front.markdown

      - name: Save pdfs and epubs
        uses: actions/upload-artifact@master
        with:
          name: export-docs
          path: publish
